# SPDX-FileCopyrightText: 2026 As Tsaqib
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "luci-app-fibocom"
SPDX-PackageSupplier = "As Tsaqib"
SPDX-PackageDownloadLocation = "NOASSERTION"

[[annotations]]
path = [
  "tests/fixtures/live/l850-mbim-connected.json",
  "tests/fixtures/ca/*.txt",
  "tests/fixtures/pci/*.txt",
  "luci-app-fibocom/root/usr/share/luci/menu.d/luci-app-fibocom.json",
  "luci-app-fibocom/root/usr/share/rpcd/acl.d/luci-app-fibocom.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 As Tsaqib"
SPDX-License-Identifier = "Apache-2.0"
