#!/bin/sh
# SPDX-FileCopyrightText: 2026 As Tsaqib
# SPDX-License-Identifier: GPL-2.0-or-later
# shellcheck disable=SC1091,SC2153

[ -r /usr/share/libubox/jshn.sh ] || exit 0
. /usr/share/libubox/jshn.sh

case "$ACTION" in
	add|remove|change|move|bind|unbind|online|offline) action="$ACTION" ;;
	*) action=change ;;
esac

json_init
json_add_string reason hotplug
json_add_string subsystem net
json_add_string action "$action"

ubus call fibocom rescan "$(json_dump)" >/dev/null 2>&1 || true
exit 0
