#!/bin/sh /etc/rc.common
# SPDX-FileCopyrightText: 2026 As Tsaqib
# SPDX-License-Identifier: GPL-2.0-or-later
# shellcheck disable=SC2034

USE_PROCD=1
START=25
STOP=85

PROG=/usr/sbin/fibocomd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --foreground --shadow
	procd_set_param respawn 3600 5 5
	procd_set_param term_timeout 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger fibocom
}
